[package]
name = "simulation_controller"
version = "0.1.0"
authors = ["{{authors}}"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
tui-big-text = "0.7.0"
rand = "0.9.0-alpha.2"
image = "0.25.5"
